#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 11 11:00:25 2024

@author: lefumaqelepo
"""

country_abbrs = {
    'Angola':'AGO',
    'Benin':'BEN',
    'Botswana':'BWA',
    'Burkina Faso':'BFA',
    'Burundi':'BDI',
    'Cameroon':'CMR',
    'Cape Verde':'CPV',
    'Cabo Verde': 'CPV',
    'Central African Republic':'CAF',
    'Chad':'TCD',
    'Comoros':'COM',
    'Congo, Rep.':'COG',
    'Congo, Dem. Rep.':'COD',
    "Cote d'Ivoire":'CIV',
    'Equatorial Guinea':'GNQ',
    'Eritrea':'ERI',
    'Ethiopia':'ETH',
    'Eswatini' : 'SWZ',
    'Gabon':'GAB',
    'Ghana':'GHA',
    'Guinea':'GIN',
    'Guinea-Bissau':'GNB',
    'Kenya':'KEN',
    'Lesotho':'LSO', 
    'Liberia':'LBR', 
    'Madagascar':'MDG', 
    'Malawi':'MWI', 
    'Mali':'MLI', 
    'Mauritania':'MRT',
    'Mauritius':'MUS', 
    'Mozambique':'MOZ', 
    'Namibia':'NAM', 
    'Niger':'NER',
    'Nigeria':'NGA', 
    'Rwanda':'RWA', 
    'Sao Tome and Principe':'STP', 
    'Senegal':'SEN', 
    'Seychelles':'SYC', 
    'Sierra Leone':'SLE', 
    'Somalia':'SOM', 
    'South Africa':'ZAF',
    'South Sudan':'SSD', 
    'Sudan':'SDN', 
    'Swaziland':'SWZ', 
    'Tanzania':'TZA', 
    'Gambia':'GMB', 
    'Togo':'TGO', 
    'Uganda':'UGA', 
    'Zambia':'ZMB', 
    'Zimbabwe':'ZWE'
    }


timezones = dict([
    ('AGO', 'Africa/Luanda'),
    ('BEN', 'Africa/Porto-Novo'),
    ('BWA', 'Africa/Gaborone'),
    ('BFA', 'Africa/Ouagadougou'),
    ('BDI', 'Africa/Bujumbura'),
    ('CMR', 'Africa/Douala'),
    ('CPV', 'Atlantic/Cape_Verde'),
    ('CAF', 'Africa/Bangui'),
    ('TCD', 'Africa/Ndjamena'),
    ('COM', 'Indian/Comoro'),
    ('COG', 'Africa/Brazzaville'),
    ('COD', 'Africa/Kinshasa'),
    ('CIV', 'Africa/Abidjan'),
    ('GNQ', 'Africa/Malabo'),
    ('ERI', 'Africa/Asmara'),
    ('ETH', 'Africa/Addis_Ababa'),
    ('GAB', 'Africa/Libreville'),
    ('GHA', 'Africa/Accra'),
    ('GIN', 'Africa/Conakry'),
    ('GNB', 'Africa/Bissau'),
    ('KEN', 'Africa/Nairobi'),
    ('LSO', 'Africa/Maseru'),
    ('LBR', 'Africa/Monrovia'),
    ('MDG', 'Indian/Antananarivo'),
    ('MWI', 'Africa/Blantyre'),
    ('MLI', 'Africa/Bamako'),
    ('MRT', 'Africa/Nouakchott'),
    ('MUS', 'Indian/Mauritius'),
    ('MOZ', 'Africa/Maputo'),
    ('NAM', 'Africa/Windhoek'),
    ('NER', 'Africa/Niamey'),
    ('NGA', 'Africa/Lagos'),
    ('RWA', 'Africa/Kigali'),
    ('STP', 'Africa/Sao_Tome'),
    ('SEN', 'Africa/Dakar'),
    ('SYC', 'Indian/Mahe'),
    ('SLE', 'Africa/Freetown'),
    ('SOM', 'Africa/Mogadishu'),
    ('ZAF', 'Africa/Johannesburg'),
    ('SSD', 'Africa/Juba'),
    ('SDN', 'Africa/Khartoum'),
    ('SWZ', 'Africa/Mbabane'),
    ('TZA', 'Africa/Dar_es_Salaam'),
    ('GMB', 'Africa/Banjul'),
    ('TGO', 'Africa/Lome'),
    ('UGA', 'Africa/Kampala'),
    ('ZMB', 'Africa/Lusaka'),
    ('ZWE', 'Africa/Harare')
    ])